[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp-serde = "1.3.0"
serde = { version = "1.0.210", features = ["derive"] }
bytes = "1.7.2"
tokio = "1.40.0"
tokio-util = { version = "0.7.12", features = ["full"]}
